name: publish

on: ["push"]
jobs:

  publish-test_cabine-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Connect to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Contruire the test_cabine Docker image
      run: 
        docker build . --tag ghcr.io/julie-b35/test_cabine:latest
        docker run ghcr.io/julie-b35/test_cabine:latest
        docker push ghcr.io/julie-b35/test_cabine:latest
